# Generated by Django 4.2.1 on 2023-05-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
