# Generated by Django 4.2.1 on 2023-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
