# Generated by Django 4.2.1 on 2023-05-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0010_category_content_type_category_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
