# Generated by Django 4.2.1 on 2023-05-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_category_content_type_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content_type',
            new_name='contentType',
        ),
    ]
