# Generated by Django 4.2.1 on 2023-05-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_content_type_category_contenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='contentType',
            new_name='content_type',
        ),
    ]
