# Generated by Django 4.2.1 on 2023-05-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_products_brand_alter_products_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='object_id',
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
