# Generated by Django 4.2.1 on 2023-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_category_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='broad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
