# Generated by Django 4.2.1 on 2023-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_products_broad_products_high_products_large'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='high',
            new_name='height',
        ),
    ]
