# Generated by Django 4.2.1 on 2023-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_products_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
