# Generated by Django 4.2.1 on 2023-05-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_products_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerts',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
