# Generated by Django 4.2.1 on 2023-05-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_recomentation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomentation',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
