# Generated by Django 4.2.1 on 2023-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_recomentation_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=15)),
            ],
        ),
    ]
