# Generated by Django 4.2.1 on 2023-06-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deviredAt',
            new_name='deliveredAt',
        ),
    ]
