# Generated by Django 4.2.1 on 2023-06-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_deviredat_order_deliveredat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
