# Generated by Django 4.2.1 on 2023-07-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextrainfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userextrainfo',
            name='user_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, primary_key=True, serialize=False),
        ),
    ]
