# Generated by Django 4.2.1 on 2023-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_userextrainfo_user_userextrainfo_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
    ]
