# Generated by Django 4.2.1 on 2023-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_order_transactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
