# Generated by Django 4.2.1 on 2023-08-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_images_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
