export const ITEM_ADD_CART = "ITEM_ADD_CART"
export const ITEM_REMOVE_CART = "ITEM_REMOVE_CART"


export const CART_SAVE_SHIPPING_ADDRESS  = "CART_SAVE_SHIPPING_ADDRESS"
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"

export const ORDER_INFO_SAVE = "ORDER_INFO_SAVE"

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"