export const PRODUCTS_GET_REQUEST = "PRODUCTS_GET_REQUEST"
export const PRODUCTS_GET_SUCCESS = "PRODUCTS_GET_SUCCESS"
export const PRODUCTS_GET_FAIL = "PRODUCTS_GET_FAIL"

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST"
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL"

export const NEWEST_PRODUCTS_GET_REQUEST = "NEWEST_PRODUCTS_GET_REQUEST"
export const NEWEST_PRODUCTS_GET_SUCCESS = "NEWEST_PRODUCTS_GET_SUCCESS"
export const NEWEST_PRODUCTS_GET_FAIL = "NEWEST_PRODUCTS_GET_FAIL"

export const OFFERSTS_GET_REQUEST = "OFFERSTS_GET_REQUEST"
export const OFFERSTS_GET_SUCCESS = "OFFERSTS_GET_SUCCESS"
export const OFFERSTS_GET_FAIL = "OFFERSTS_GET_FAIL"

export const RECOMENDATIONS_GET_REQUEST = "RECOMENDATIONS_GET_REQUEST"
export const RECOMENDATIONS_GET_SUCCESS = "RECOMENDATIONS_GET_SUCCESS"
export const RECOMENDATIONS_GET_FAIL = "RECOMENDATIONS_GET_FAIL"

export const CATEGORY_PRODUCTS_GET_REQUEST = "CATEGORY_PRODUCTS_GET_REQUEST"
export const CATEGORY_PRODUCTS_GET_SUCCESS = "CATEGORY_PRODUCTS_GET_SUCCESS"
export const CATEGORY_PRODUCTS_GET_FAIL = "CATEGORY_PRODUCTS_GET_FAIL"

export const SEARCH_PRODUCTS_GET_REQUEST = "SEARCH_PRODUCTS_GET_REQUEST"
export const SEARCH_PRODUCTS_GET_SUCCESS = "SEARCH_PRODUCTS_GET_SUCCESS"
export const SEARCH_PRODUCTS_GET_FAIL = "SEARCH_PRODUCTS_GET_FAIL"