export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"

export const USER_EXTRAINFO_GET_REQUEST = "USER_EXTRAINFO_GET_REQUEST"
export const USER_EXTRAINFO_GET_SUCCESS = "USER_EXTRAINFO_GET_SUCCESS"
export const USER_EXTRAINFO_GET_FAIL = "USER_EXTRAINFO_GET_FAIL"

export const GET_TOKEN_AUTHENTICATION_REQUEST = "GET_TOKEN_AUTHENTICATION_REQUEST"
export const GET_TOKEN_AUTHENTICATION_SUCCESS = "GET_TOKEN_AUTHENTICATION_SUCCESS"
export const GET_TOKEN_AUTHENTICATION_FAIL = "GET_TOKEN_AUTHENTICATION_FAIL"

export const GET_USERINFO_REQUEST = "GET_USERINFO_REQUEST"
export const GET_USERINFO_SUCCESS = "GET_USERINFO_SUCCESS"
export const GET_USERINFO_FAIL = "GET_USERINFO_FAIL"
export const ERROR = 'ERROR'